### ISSUE TITLE
Group Id is not visible

### ISSUE THREAD

**Issue by 2m** [kitlangton/scala-interactive-update#13]
Awesome job on this tool. :) While trying it out on different projects, I noticed this little nitpick.

Some libraries, like sttp, have the library name only in the group id. So the following library dependencies:

```
  "com.softwaremill.sttp.client3" %% "core"           % "3.6.1",
  "com.softwaremill.sttp.client3" %% "circe"          % "3.6.1",
  "com.softwaremill.sttp.client3" %% "scribe-backend" % "3.6.1",
  "io.circe"                      %% "circe-generic"  % "0.14.1"
```

produce the following

<img width="384" alt="image" src="https://user-images.githubusercontent.com/422086/176094553-8d6c77f6-7137-43ae-acdb-1209802034f1.png">

This makes it hard to distinguish sttp library for circe support from the circe library itself.

**Comment by kitlangton** [comment]
Great suggestion! I’ll add this :)

**Comment by kitlangton** [comment]
Whee:


https://user-images.githubusercontent.com/7587245/176197669-9ee02e07-cef8-4865-b031-c2bc4fdeca77.mp4

**Comment by 2m** [comment]
Perfect, thank you!
