### ISSUE TITLE
Feature request: plugins

### ISSUE THREAD

**Issue by kubukoz** [kitlangton/scala-interactive-update#3]
It would be great if the app supported updating sbt plugins.

**Comment by kitlangton** [comment]
<img width="560" alt="CleanShot 2022-06-27 at 13 52 10@2x" src="https://user-images.githubusercontent.com/7587245/176004611-2898fab5-197a-44d4-b32a-619a98f9aef3.png">

Added support :)

**Comment by matthughes** [comment]
FWIW this doesn't seem to work for me.  Have usual project/plugins.sbt but it didn't notice an upgraded scalajs plugin.
